"project_id" : "577761"
"base_path" : "."
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true

files: [
 {
  "source" : "/EurekaTrackerAutoPopper/Resources/Language.resx",
  "translation" : "/EurekaTrackerAutoPopper/Resources/Language.%two_letters_code%.resx",
  "dest" : "/Language.resx",
  "skip_untranslated_strings": true,
 }
]
