//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EurekaTrackerAutoPopper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EurekaTrackerAutoPopper.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string AboutEntryAuthor {
            get {
                return ResourceManager.GetString("AboutEntryAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord:.
        /// </summary>
        internal static string AboutEntryDiscord {
            get {
                return ResourceManager.GetString("AboutEntryDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string AboutEntryVersion {
            get {
                return ResourceManager.GetString("AboutEntryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anemos.
        /// </summary>
        internal static string AreaNameAnemos {
            get {
                return ResourceManager.GetString("AreaNameAnemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydatos.
        /// </summary>
        internal static string AreaNameHydatos {
            get {
                return ResourceManager.GetString("AreaNameHydatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos.
        /// </summary>
        internal static string AreaNamePagos {
            get {
                return ResourceManager.GetString("AreaNamePagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyros.
        /// </summary>
        internal static string AreaNamePyros {
            get {
                return ResourceManager.GetString("AreaNamePyros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawning in:.
        /// </summary>
        internal static string BunnyWindowRespawning {
            get {
                return ResourceManager.GetString("BunnyWindowRespawning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  soon .
        /// </summary>
        internal static string BunnyWindowRespawningsoon {
            get {
                return ResourceManager.GetString("BunnyWindowRespawningsoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alive.
        /// </summary>
        internal static string BunnyWindowStatusAlive {
            get {
                return ResourceManager.GetString("BunnyWindowStatusAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string BunnyWindowStatusUnknown {
            get {
                return ResourceManager.GetString("BunnyWindowStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Helper Window.
        /// </summary>
        internal static string ButtonOpenHelper {
            get {
                return ResourceManager.GetString("ButtonOpenHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Underway.
        /// </summary>
        internal static string CEStateBattle {
            get {
                return ResourceManager.GetString("CEStateBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string CEStateInactive {
            get {
                return ResourceManager.GetString("CEStateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiting Members.
        /// </summary>
        internal static string CEStateRegister {
            get {
                return ResourceManager.GetString("CEStateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing To Commence.
        /// </summary>
        internal static string CEStateWarmup {
            get {
                return ResourceManager.GetString("CEStateWarmup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing inactive fairies from tracking..
        /// </summary>
        internal static string ChatDeadFairyNote {
            get {
                return ResourceManager.GetString("ChatDeadFairyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to place fairy markers on map.
        /// </summary>
        internal static string ChatErrorFairyMapMarkers {
            get {
                return ResourceManager.GetString("ChatErrorFairyMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking for fairies needs to be reset, please go to all listed locations to update..
        /// </summary>
        internal static string ChatErrorFairyMarkers {
            get {
                return ResourceManager.GetString("ChatErrorFairyMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to place fairy markers on minimap.
        /// </summary>
        internal static string ChatErrorFairyMinimapMarkers {
            get {
                return ResourceManager.GetString("ChatErrorFairyMinimapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to place all markers on map.
        /// </summary>
        internal static string ChatErrorMapMarkers {
            get {
                return ResourceManager.GetString("ChatErrorMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to place all markers on minimap.
        /// </summary>
        internal static string ChatErrorMinimapMarkers {
            get {
                return ResourceManager.GetString("ChatErrorMinimapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in Eureka, this command is unavailable..
        /// </summary>
        internal static string ChatErrorNotInEureka {
            get {
                return ResourceManager.GetString("ChatErrorNotInEureka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve found a new chest location.
        /// </summary>
        internal static string ChatNewChestFound {
            get {
                return ResourceManager.GetString("ChatNewChestFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider sending the following information to the developer:.
        /// </summary>
        internal static string ChatNewChestFoundDevNote {
            get {
                return ResourceManager.GetString("ChatNewChestFoundDevNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please do not use the feedback function to send this).
        /// </summary>
        internal static string ChatNewChestFoundFeedback {
            get {
                return ResourceManager.GetString("ChatNewChestFoundFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Previous Engagements.
        /// </summary>
        internal static string CollapseablePreviousEngagements {
            get {
                return ResourceManager.GetString("CollapseablePreviousEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Markers.
        /// </summary>
        internal static string ConfigButtonAddMapMarkers {
            get {
                return ResourceManager.GetString("ConfigButtonAddMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string ConfigButtonCirclePreview {
            get {
                return ResourceManager.GetString("ConfigButtonCirclePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Thread.
        /// </summary>
        internal static string ConfigButtonDiscordForumThread {
            get {
                return ResourceManager.GetString("ConfigButtonDiscordForumThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo All.
        /// </summary>
        internal static string ConfigButtonFairyAll {
            get {
                return ResourceManager.GetString("ConfigButtonFairyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues.
        /// </summary>
        internal static string ConfigButtonGithubIssues {
            get {
                return ResourceManager.GetString("ConfigButtonGithubIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Markers.
        /// </summary>
        internal static string ConfigButtonRemoveMapMarkers {
            get {
                return ResourceManager.GetString("ConfigButtonRemoveMapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Tracker.
        /// </summary>
        internal static string ConfigButtonStartNew {
            get {
                return ResourceManager.GetString("ConfigButtonStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunny.
        /// </summary>
        internal static string ConfigHeaderBunny {
            get {
                return ResourceManager.GetString("ConfigHeaderBunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunny Carrot.
        /// </summary>
        internal static string ConfigHeaderBunnyCarrot {
            get {
                return ResourceManager.GetString("ConfigHeaderBunnyCarrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagements.
        /// </summary>
        internal static string ConfigHeaderEngagements {
            get {
                return ResourceManager.GetString("ConfigHeaderEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy / Elemental.
        /// </summary>
        internal static string ConfigHeaderFairy {
            get {
                return ResourceManager.GetString("ConfigHeaderFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string ConfigHeaderFormat {
            get {
                return ResourceManager.GetString("ConfigHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ConfigHeaderGeneral {
            get {
                return ResourceManager.GetString("ConfigHeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Locations.
        /// </summary>
        internal static string ConfigHeaderKnownLocations {
            get {
                return ResourceManager.GetString("ConfigHeaderKnownLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Stats:.
        /// </summary>
        internal static string ConfigHeaderMapStats {
            get {
                return ResourceManager.GetString("ConfigHeaderMapStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Marker.
        /// </summary>
        internal static string ConfigHeaderMarkerSetHeader {
            get {
                return ResourceManager.GetString("ConfigHeaderMarkerSetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        internal static string ConfigHeaderPop {
            get {
                return ResourceManager.GetString("ConfigHeaderPop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot Helper Window.
        /// </summary>
        internal static string ConfigHeaderPotHelperHeader {
            get {
                return ResourceManager.GetString("ConfigHeaderPotHelperHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity Notification.
        /// </summary>
        internal static string ConfigHeaderProximityNotification {
            get {
                return ResourceManager.GetString("ConfigHeaderProximityNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stats:.
        /// </summary>
        internal static string ConfigHeaderTotalStats {
            get {
                return ResourceManager.GetString("ConfigHeaderTotalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forked Tower.
        /// </summary>
        internal static string ConfigHeaderTower {
            get {
                return ResourceManager.GetString("ConfigHeaderTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker:.
        /// </summary>
        internal static string ConfigHeaderTracker {
            get {
                return ResourceManager.GetString("ConfigHeaderTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure.
        /// </summary>
        internal static string ConfigHeaderTreasure {
            get {
                return ResourceManager.GetString("ConfigHeaderTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ConfigInputPW {
            get {
                return ResourceManager.GetString("ConfigInputPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance URL.
        /// </summary>
        internal static string ConfigInputURL {
            get {
                return ResourceManager.GetString("ConfigInputURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To Pot Markers Automatically.
        /// </summary>
        internal static string ConfigOptionAutoPots {
            get {
                return ResourceManager.GetString("ConfigOptionAutoPots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Low Level.
        /// </summary>
        internal static string ConfigOptionBunnyLowLevelFates {
            get {
                return ResourceManager.GetString("ConfigOptionBunnyLowLevelFates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window on Entry.
        /// </summary>
        internal static string ConfigOptionBunnyWindow {
            get {
                return ResourceManager.GetString("ConfigOptionBunnyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Memory.
        /// </summary>
        internal static string ConfigOptionClearMemory {
            get {
                return ResourceManager.GetString("ConfigOptionClearMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coffer Icons on Entry.
        /// </summary>
        internal static string ConfigOptionCofferIcons {
            get {
                return ResourceManager.GetString("ConfigOptionCofferIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Shout Message.
        /// </summary>
        internal static string ConfigOptionCopyShoutMessage {
            get {
                return ResourceManager.GetString("ConfigOptionCopyShoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Nearby Coffer Circle.
        /// </summary>
        internal static string ConfigOptionDrawCircle {
            get {
                return ResourceManager.GetString("ConfigOptionDrawCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo In Chat.
        /// </summary>
        internal static string ConfigOptionEcho {
            get {
                return ResourceManager.GetString("ConfigOptionEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        internal static string ConfigOptionEchoFairy {
            get {
                return ResourceManager.GetString("ConfigOptionEchoFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        internal static string ConfigOptionEchoNM {
            get {
                return ResourceManager.GetString("ConfigOptionEchoNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide In Critical Encounters.
        /// </summary>
        internal static string ConfigOptionEngagementsHide {
            get {
                return ResourceManager.GetString("ConfigOptionEngagementsHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Active Pot.
        /// </summary>
        internal static string ConfigOptionEngagementsPot {
            get {
                return ResourceManager.GetString("ConfigOptionEngagementsPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Fast Switch Overlay.
        /// </summary>
        internal static string ConfigOptionFastSwitcher {
            get {
                return ResourceManager.GetString("ConfigOptionFastSwitcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Fate Window On Entry.
        /// </summary>
        internal static string ConfigOptionFateWindow {
            get {
                return ResourceManager.GetString("ConfigOptionFateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Map Flag.
        /// </summary>
        internal static string ConfigOptionFlag {
            get {
                return ResourceManager.GetString("ConfigOptionFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear After Seconds.
        /// </summary>
        internal static string ConfigOptionMemoryTimer {
            get {
                return ResourceManager.GetString("ConfigOptionMemoryTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Shout Window.
        /// </summary>
        internal static string ConfigOptionOpenShoutWindow {
            get {
                return ResourceManager.GetString("ConfigOptionOpenShoutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place After Entering.
        /// </summary>
        internal static string ConfigOptionPlaceDefault {
            get {
                return ResourceManager.GetString("ConfigOptionPlaceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize Map Coords.
        /// </summary>
        internal static string ConfigOptionRandomizeCoords {
            get {
                return ResourceManager.GetString("ConfigOptionRandomizeCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Short Names.
        /// </summary>
        internal static string ConfigOptionShortNames {
            get {
                return ResourceManager.GetString("ConfigOptionShortNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PT in Shout Window.
        /// </summary>
        internal static string ConfigOptionShowPT {
            get {
                return ResourceManager.GetString("ConfigOptionShowPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Critical Encounter Sound.
        /// </summary>
        internal static string ConfigOptionSoundCESpawn {
            get {
                return ResourceManager.GetString("ConfigOptionSoundCESpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Fate Sound.
        /// </summary>
        internal static string ConfigOptionSoundFateSpawn {
            get {
                return ResourceManager.GetString("ConfigOptionSoundFateSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound.
        /// </summary>
        internal static string ConfigOptionSoundNM {
            get {
                return ResourceManager.GetString("ConfigOptionSoundNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Tower Sound.
        /// </summary>
        internal static string ConfigOptionSoundTowerSpawn {
            get {
                return ResourceManager.GetString("ConfigOptionSoundTowerSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Spawn Sound.
        /// </summary>
        internal static string ConfigOptionSpawnNotification {
            get {
                return ResourceManager.GetString("ConfigOptionSpawnNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Below Map.
        /// </summary>
        internal static string ConfigOptionSwitcherPosition {
            get {
                return ResourceManager.GetString("ConfigOptionSwitcherPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast.
        /// </summary>
        internal static string ConfigOptionToast {
            get {
                return ResourceManager.GetString("ConfigOptionToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast.
        /// </summary>
        internal static string ConfigOptionToastFairy {
            get {
                return ResourceManager.GetString("ConfigOptionToastFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toast.
        /// </summary>
        internal static string ConfigOptionToastNM {
            get {
                return ResourceManager.GetString("ConfigOptionToastNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tab Name.
        /// </summary>
        internal static string ConfigOptionTowerTabName {
            get {
                return ResourceManager.GetString("ConfigOptionTowerTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a small indicator &quot;(active)&quot; to the tab name if tower is active..
        /// </summary>
        internal static string ConfigOptionTowerTabTooltip {
            get {
                return ResourceManager.GetString("ConfigOptionTowerTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 12-hour Format.
        /// </summary>
        internal static string ConfigOptionUse12h {
            get {
                return ResourceManager.GetString("ConfigOptionUse12h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Eorzea Time instead.
        /// </summary>
        internal static string ConfigOptionUseET {
            get {
                return ResourceManager.GetString("ConfigOptionUseET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically display pot treasure locations on the map when you have a pot following you..
        /// </summary>
        internal static string ConfigTooltipAutoPots {
            get {
                return ResourceManager.GetString("ConfigTooltipAutoPots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only shows the low level bunny fates for Pagos and Pyros..
        /// </summary>
        internal static string ConfigTooltipBunnyLowLevelFates {
            get {
                return ResourceManager.GetString("ConfigTooltipBunnyLowLevelFates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or use the command &apos;/elbunny&apos;..
        /// </summary>
        internal static string ConfigTooltipBunnyWindow {
            get {
                return ResourceManager.GetString("ConfigTooltipBunnyWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove spotted treasure and carrots, after X Seconds of being unseen, so that notifications can reappear..
        /// </summary>
        internal static string ConfigTooltipClearMemory {
            get {
                return ResourceManager.GetString("ConfigTooltipClearMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the coffer locations on entry of eureka..
        /// </summary>
        internal static string ConfigTooltipCofferIcons {
            get {
                return ResourceManager.GetString("ConfigTooltipCofferIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws a circle if the player is near a coffer location..
        /// </summary>
        internal static string ConfigTooltipDrawCircle {
            get {
                return ResourceManager.GetString("ConfigTooltipDrawCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tracker in Browser.
        /// </summary>
        internal static string ConfigTooltipOpenTracker {
            get {
                return ResourceManager.GetString("ConfigTooltipOpenTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling this option will remove time element from the shout message..
        /// </summary>
        internal static string ConfigTooltipShowPT {
            get {
                return ResourceManager.GetString("ConfigTooltipShowPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only available while in eureka.
        /// </summary>
        internal static string ConfigTooltipStartNew {
            get {
                return ResourceManager.GetString("ConfigTooltipStartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen: {0} ago.
        /// </summary>
        internal static string FateInfoLastSeen {
            get {
                return ResourceManager.GetString("FateInfoLastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen: not seen.
        /// </summary>
        internal static string FateInfoLastSeenUnknown {
            get {
                return ResourceManager.GetString("FateInfoLastSeenUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn Times: [{0}].
        /// </summary>
        internal static string FateInfoRespawnTimes {
            get {
                return ResourceManager.GetString("FateInfoRespawnTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking Time: {0}.
        /// </summary>
        internal static string FateInfoWalkingTime {
            get {
                return ResourceManager.GetString("FateInfoWalkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string FateProgress {
            get {
                return ResourceManager.GetString("FateProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string FateTimeRemaining {
            get {
                return ResourceManager.GetString("FateTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where can I join an organized run? (Click name).
        /// </summary>
        internal static string ForkedTowerInfoJoinDiscordList {
            get {
                return ResourceManager.GetString("ForkedTowerInfoJoinDiscordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to join a Forked Tower run?.
        /// </summary>
        internal static string ForkedTowerInfoJoinRun {
            get {
                return ResourceManager.GetString("ForkedTowerInfoJoinRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players on Platform (Level 20 or above): {0}.
        /// </summary>
        internal static string ForkedTowerInfoPlayerCount {
            get {
                return ResourceManager.GetString("ForkedTowerInfoPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player List.
        /// </summary>
        internal static string ForkedTowerInfoPlayerListCollapseable {
            get {
                return ResourceManager.GetString("ForkedTowerInfoPlayerListCollapseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that attempting to join Forked Tower as an individual player is highly discouraged. This means to stand on the tower platform during the prerequisite weather conditions, in addition to offering any amount of ciphers for entry during this period..
        /// </summary>
        internal static string ForkedTowerInfoWarning1 {
            get {
                return ResourceManager.GetString("ForkedTowerInfoWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to learn more about Forked Tower or would like to participate in an organized group, it&apos;s encouraged to join one of the following Discord servers for your respective region..
        /// </summary>
        internal static string ForkedTowerInfoWarning2 {
            get {
                return ResourceManager.GetString("ForkedTowerInfoWarning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not on the Platform..
        /// </summary>
        internal static string ForkedTowerNotOnPlatform {
            get {
                return ResourceManager.GetString("ForkedTowerNotOnPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forked Tower hasn&apos;t been seen yet..
        /// </summary>
        internal static string ForkedTowerNotSeen {
            get {
                return ResourceManager.GetString("ForkedTowerNotSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Critical Encounter:.
        /// </summary>
        internal static string HeaderActiveCE {
            get {
                return ResourceManager.GetString("HeaderActiveCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active FATE:.
        /// </summary>
        internal static string HeaderActiveFate {
            get {
                return ResourceManager.GetString("HeaderActiveFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Pot FATE:.
        /// </summary>
        internal static string HeaderActivePot {
            get {
                return ResourceManager.GetString("HeaderActivePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Encounter:.
        /// </summary>
        internal static string HeaderCE {
            get {
                return ResourceManager.GetString("HeaderCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATEs:.
        /// </summary>
        internal static string HeaderFates {
            get {
                return ResourceManager.GetString("HeaderFates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire and Earth.
        /// </summary>
        internal static string LogCategoryFE {
            get {
                return ResourceManager.GetString("LogCategoryFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice and Lighting.
        /// </summary>
        internal static string LogCategoryIL {
            get {
                return ResourceManager.GetString("LogCategoryIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string LogCategoryNight {
            get {
                return ResourceManager.GetString("LogCategoryNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprites.
        /// </summary>
        internal static string LogCategorySprites {
            get {
                return ResourceManager.GetString("LogCategorySprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water and Wind.
        /// </summary>
        internal static string LogCategoryWW {
            get {
                return ResourceManager.GetString("LogCategoryWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read log..
        /// </summary>
        internal static string LogError {
            get {
                return ResourceManager.GetString("LogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing is necessary as the game has to request updated progress from the server.
        ///A cooldown of 5s applies after each use..
        /// </summary>
        internal static string LogWindowRefreshTooltip {
            get {
                return ResourceManager.GetString("LogWindowRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open your challenge log in the &apos;Field Operations&apos; category..
        /// </summary>
        internal static string LogWrongTab {
            get {
                return ResourceManager.GetString("LogWrongTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect eureka progress..
        /// </summary>
        internal static string LogWrongTabNote {
            get {
                return ResourceManager.GetString("LogWrongTabNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunny Carrot Locations.
        /// </summary>
        internal static string MarkerSetBunny {
            get {
                return ResourceManager.GetString("MarkerSetBunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure And Carrots.
        /// </summary>
        internal static string MarkerSetCombined {
            get {
                return ResourceManager.GetString("MarkerSetCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show None.
        /// </summary>
        internal static string MarkerSetNone {
            get {
                return ResourceManager.GetString("MarkerSetNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Treasure.
        /// </summary>
        internal static string MarkerSetOnlyBronze {
            get {
                return ResourceManager.GetString("MarkerSetOnlyBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Treasure.
        /// </summary>
        internal static string MarkerSetOnlySilver {
            get {
                return ResourceManager.GetString("MarkerSetOnlySilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot Locations.
        /// </summary>
        internal static string MarkerSetPot {
            get {
                return ResourceManager.GetString("MarkerSetPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Treasure.
        /// </summary>
        internal static string MarkerSetTreasure {
            get {
                return ResourceManager.GetString("MarkerSetTreasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (active).
        /// </summary>
        internal static string OccultTowerActiveIndicator {
            get {
                return ResourceManager.GetString("OccultTowerActiveIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t in the occult territory, this window is not of any use..
        /// </summary>
        internal static string OccultWindowNotInTerritory {
            get {
                return ResourceManager.GetString("OccultWindowNotInTerritory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetheryte Unlocks:.
        /// </summary>
        internal static string QuestLogAetheryteText {
            get {
                return ResourceManager.GetString("QuestLogAetheryteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the The Val River Swale near the waterfall and interact with the Confluence.
        /// </summary>
        internal static string QuestLogAnemos13Step2 {
            get {
                return ResourceManager.GetString("QuestLogAnemos13Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the Uncanny Valley and interact with the Confluence.
        /// </summary>
        internal static string QuestLogAnemos17Step2 {
            get {
                return ResourceManager.GetString("QuestLogAnemos17Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the Aethernet Control and interact with the Aethernet Relay.
        /// </summary>
        internal static string QuestLogAnemos17Step4 {
            get {
                return ResourceManager.GetString("QuestLogAnemos17Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with the Aethernet Relay again and trade in 99 Anemos Crystals..
        /// </summary>
        internal static string QuestLogAnemos17Step5 {
            get {
                return ResourceManager.GetString("QuestLogAnemos17Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Krile and Gerolt.
        /// </summary>
        internal static string QuestLogAnemos1Step1 {
            get {
                return ResourceManager.GetString("QuestLogAnemos1Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must obtain a Protean Crystal from a normal monster..
        /// </summary>
        internal static string QuestLogAnemos1Tip1 {
            get {
                return ResourceManager.GetString("QuestLogAnemos1Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot exchange Anemos Crystals for Protean Crystals until you finish this quest..
        /// </summary>
        internal static string QuestLogAnemos1Tip2 {
            get {
                return ResourceManager.GetString("QuestLogAnemos1Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed inside the Early Natural History Society Observatory and interact with the Confluence.
        /// </summary>
        internal static string QuestLogAnemos3Step2 {
            get {
                return ResourceManager.GetString("QuestLogAnemos3Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobs will spawn around and inside the building during nighttime and as such it is recommended to do this during daytime (6am to 6pm ET)..
        /// </summary>
        internal static string QuestLogAnemos3Tip1 {
            get {
                return ResourceManager.GetString("QuestLogAnemos3Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to the The Orchard below the cliff and interact with the Confluence.
        /// </summary>
        internal static string QuestLogAnemos5Step2 {
            get {
                return ResourceManager.GetString("QuestLogAnemos5Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Area.
        /// </summary>
        internal static string QuestLogHeader {
            get {
                return ResourceManager.GetString("QuestLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Central Columns and talk again to Krile.
        /// </summary>
        internal static string QuestLogHydatos51Step2 {
            get {
                return ResourceManager.GetString("QuestLogHydatos51Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed south to The Val River Source and find the Pooled Aether.
        /// </summary>
        internal static string QuestLogHydatos51Step3 {
            get {
                return ResourceManager.GetString("QuestLogHydatos51Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the The Central Columns and talk to Krile.
        /// </summary>
        internal static string QuestLogHydatos51Step4 {
            get {
                return ResourceManager.GetString("QuestLogHydatos51Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Western Columns and talk again to Krile.
        /// </summary>
        internal static string QuestLogHydatos54Step2 {
            get {
                return ResourceManager.GetString("QuestLogHydatos54Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The West Val River Bank.
        /// </summary>
        internal static string QuestLogHydatos54Step3 {
            get {
                return ResourceManager.GetString("QuestLogHydatos54Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk up the large column to find the Pooled Aether.
        /// </summary>
        internal static string QuestLogHydatos54Step4 {
            get {
                return ResourceManager.GetString("QuestLogHydatos54Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to The Western Columns and talk to Krile.
        /// </summary>
        internal static string QuestLogHydatos54Step5 {
            get {
                return ResourceManager.GetString("QuestLogHydatos54Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Krile at the The Western Columns.
        /// </summary>
        internal static string QuestLogHydatos57Step1 {
            get {
                return ResourceManager.GetString("QuestLogHydatos57Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed east to The Eastern Columns and talk to Krile again.
        /// </summary>
        internal static string QuestLogHydatos57Step2 {
            get {
                return ResourceManager.GetString("QuestLogHydatos57Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head north to The East Val River Bank to find the Pooled Aether.
        /// </summary>
        internal static string QuestLogHydatos57Step3 {
            get {
                return ResourceManager.GetString("QuestLogHydatos57Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to The Eastern Columns and talk to Krile.
        /// </summary>
        internal static string QuestLogHydatos57Step4 {
            get {
                return ResourceManager.GetString("QuestLogHydatos57Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to The Eastern Columns and talk to Krile.
        /// </summary>
        internal static string QuestLogHydatos60Step1 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to The Aetherbridge Foundation and talk again to Krile.
        /// </summary>
        internal static string QuestLogHydatos60Step2 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed into the Headquarters Entrance (Teleport next to you).
        /// </summary>
        internal static string QuestLogHydatos60Step3 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk again to Krile.
        /// </summary>
        internal static string QuestLogHydatos60Step4 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go in the Board Room and talk again to Krile.
        /// </summary>
        internal static string QuestLogHydatos60Step5 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with the Scattered Tomes.
        /// </summary>
        internal static string QuestLogHydatos60Step6 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk again to Krile (a few cutscenes will play).
        /// </summary>
        internal static string QuestLogHydatos60Step7 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose between Krile&apos;s path (sealing) or that of Ejika Tsunjika (destruction).
        /// </summary>
        internal static string QuestLogHydatos60Step8 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Central Point and talk to Ejika Tsunjika or Krile (opposite you picked).
        /// </summary>
        internal static string QuestLogHydatos60Step9 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Step9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quest unlocks The Baldesion Arsenal..
        /// </summary>
        internal static string QuestLogHydatos60Tip1 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak with the Expedition Scholar after finishing this quest..
        /// </summary>
        internal static string QuestLogHydatos60Tip2 {
            get {
                return ResourceManager.GetString("QuestLogHydatos60Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not In Eureka....
        /// </summary>
        internal static string QuestLogOutside {
            get {
                return ResourceManager.GetString("QuestLogOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the Depleted Aetherial Stream at The Cones (upper level on a raised grassy hill).
        /// </summary>
        internal static string QuestLogPagos21Step2 {
            get {
                return ResourceManager.GetString("QuestLogPagos21Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the Depleted Aetherial Stream at The Val River Belly.
        /// </summary>
        internal static string QuestLogPagos23Step2 {
            get {
                return ResourceManager.GetString("QuestLogPagos23Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the magicite at The Eastern Edge.
        /// </summary>
        internal static string QuestLogPagos25Step2 {
            get {
                return ResourceManager.GetString("QuestLogPagos25Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interact with it again in almost the same location.
        /// </summary>
        internal static string QuestLogPagos25Step3 {
            get {
                return ResourceManager.GetString("QuestLogPagos25Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also speak with Gerolt any time after first speaking to Krile to unlock Eureka Pagos weapon enhancement..
        /// </summary>
        internal static string QuestLogPagos25Tip1 {
            get {
                return ResourceManager.GetString("QuestLogPagos25Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop down here.
        /// </summary>
        internal static string QuestLogPagos29Step2 {
            get {
                return ResourceManager.GetString("QuestLogPagos29Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Ejika Tsunjika.
        /// </summary>
        internal static string QuestLogPagos29Step3 {
            get {
                return ResourceManager.GetString("QuestLogPagos29Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the aether column at The Fumarole.
        /// </summary>
        internal static string QuestLogPagos35Step2 {
            get {
                return ResourceManager.GetString("QuestLogPagos35Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Living Foundry and talk to Krile.
        /// </summary>
        internal static string QuestLogPyros35Step2 {
            get {
                return ResourceManager.GetString("QuestLogPyros35Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Logos Manipulator and select the Paralyze L logogram and extract the mneme.
        /// </summary>
        internal static string QuestLogPyros35Step5 {
            get {
                return ResourceManager.GetString("QuestLogPyros35Step5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Northeastern Ice Needles and interact with the confluence.
        /// </summary>
        internal static string QuestLogPyros35Step7 {
            get {
                return ResourceManager.GetString("QuestLogPyros35Step7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Surgate Town House and interact with the Promising Scrap.
        /// </summary>
        internal static string QuestLogPyros38Step2 {
            get {
                return ResourceManager.GetString("QuestLogPyros38Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Firing Chamber and interact with the confluence.
        /// </summary>
        internal static string QuestLogPyros38Step4 {
            get {
                return ResourceManager.GetString("QuestLogPyros38Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This quest unlocks additional capacity for the logos manipulator..
        /// </summary>
        internal static string QuestLogPyros38Tip1 {
            get {
                return ResourceManager.GetString("QuestLogPyros38Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to West Flamerock and interact with the confluence.
        /// </summary>
        internal static string QuestLogPyros40Step2 {
            get {
                return ResourceManager.GetString("QuestLogPyros40Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Krile (a few cutscenes will play).
        /// </summary>
        internal static string QuestLogPyros45Step1 {
            get {
                return ResourceManager.GetString("QuestLogPyros45Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Living Foundry and talk to Krile.
        /// </summary>
        internal static string QuestLogPyros45Step2 {
            get {
                return ResourceManager.GetString("QuestLogPyros45Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to East Flamerock and interact with the confluence.
        /// </summary>
        internal static string QuestLogPyros50Step2 {
            get {
                return ResourceManager.GetString("QuestLogPyros50Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to The Cavern of the Second Cant and interact with the confluence.
        /// </summary>
        internal static string QuestLogPyros50Step4 {
            get {
                return ResourceManager.GetString("QuestLogPyros50Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Drake.
        /// </summary>
        internal static string QuestLogReturnToDrake {
            get {
                return ResourceManager.GetString("QuestLogReturnToDrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Gerolt.
        /// </summary>
        internal static string QuestLogReturnToGerolt {
            get {
                return ResourceManager.GetString("QuestLogReturnToGerolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Krile.
        /// </summary>
        internal static string QuestLogReturnToKrile {
            get {
                return ResourceManager.GetString("QuestLogReturnToKrile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string QuestLogTabItemQuestLevel {
            get {
                return ResourceManager.GetString("QuestLogTabItemQuestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Drake.
        /// </summary>
        internal static string QuestLogTalkToDrake {
            get {
                return ResourceManager.GetString("QuestLogTalkToDrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Gerolt.
        /// </summary>
        internal static string QuestLogTalkToGerolt {
            get {
                return ResourceManager.GetString("QuestLogTalkToGerolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Krile.
        /// </summary>
        internal static string QuestLogTalkToKrile {
            get {
                return ResourceManager.GetString("QuestLogTalkToKrile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ShoutButtonClose {
            get {
                return ResourceManager.GetString("ShoutButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string ShoutButtonPost {
            get {
                return ResourceManager.GetString("ShoutButtonPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout will be available 20s after spawn..
        /// </summary>
        internal static string ShoutWindowLimit {
            get {
                return ResourceManager.GetString("ShoutWindowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze:.
        /// </summary>
        internal static string StatsEntryBronze {
            get {
                return ResourceManager.GetString("StatsEntryBronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffers Found:.
        /// </summary>
        internal static string StatsEntryFound {
            get {
                return ResourceManager.GetString("StatsEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold:.
        /// </summary>
        internal static string StatsEntryGold {
            get {
                return ResourceManager.GetString("StatsEntryGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed Bunnies:.
        /// </summary>
        internal static string StatsEntryKilled {
            get {
                return ResourceManager.GetString("StatsEntryKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver:.
        /// </summary>
        internal static string StatsEntrySilver {
            get {
                return ResourceManager.GetString("StatsEntrySilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in Eureka:.
        /// </summary>
        internal static string StatsEntryTime {
            get {
                return ResourceManager.GetString("StatsEntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TabHeaderAbout {
            get {
                return ResourceManager.GetString("TabHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunny.
        /// </summary>
        internal static string TabHeaderBunny {
            get {
                return ResourceManager.GetString("TabHeaderBunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string TabHeaderChat {
            get {
                return ResourceManager.GetString("TabHeaderChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagements.
        /// </summary>
        internal static string TabHeaderEngagements {
            get {
                return ResourceManager.GetString("TabHeaderEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairy.
        /// </summary>
        internal static string TabHeaderFairy {
            get {
                return ResourceManager.GetString("TabHeaderFairy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TabHeaderGeneral {
            get {
                return ResourceManager.GetString("TabHeaderGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helper.
        /// </summary>
        internal static string TabHeaderHelper {
            get {
                return ResourceManager.GetString("TabHeaderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string TabHeaderMap {
            get {
                return ResourceManager.GetString("TabHeaderMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string TabHeaderNotification {
            get {
                return ResourceManager.GetString("TabHeaderNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occult.
        /// </summary>
        internal static string TabHeaderOccult {
            get {
                return ResourceManager.GetString("TabHeaderOccult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot.
        /// </summary>
        internal static string TabHeaderPot {
            get {
                return ResourceManager.GetString("TabHeaderPot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string TabHeaderStats {
            get {
                return ResourceManager.GetString("TabHeaderStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forked Tower.
        /// </summary>
        internal static string TabHeaderTower {
            get {
                return ResourceManager.GetString("TabHeaderTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker.
        /// </summary>
        internal static string TabHeaderTracker {
            get {
                return ResourceManager.GetString("TabHeaderTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TableLabelDone {
            get {
                return ResourceManager.GetString("TableLabelDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy Level.
        /// </summary>
        internal static string TableLabelEnemyLvl {
            get {
                return ResourceManager.GetString("TableLabelEnemyLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string TableLabelMonster {
            get {
                return ResourceManager.GetString("TableLabelMonster", resourceCulture);
            }
        }
    }
}
